<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hazel 005946282">

<title>Biostat 203B Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="hw2_sol_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw2_sol_files/libs/quarto-html/quarto.js"></script>
<script src="hw2_sol_files/libs/quarto-html/popper.min.js"></script>
<script src="hw2_sol_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw2_sol_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw2_sol_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw2_sol_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw2_sol_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw2_sol_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw2_sol_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" id="toc-q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="nav-link active" data-scroll-target="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="toc-section-number">1</span>  Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</a></li>
  <li><a href="#q2.-icu-stays" id="toc-q2.-icu-stays" class="nav-link" data-scroll-target="#q2.-icu-stays"><span class="toc-section-number">2</span>  Q2. ICU stays</a></li>
  <li><a href="#q3.-admission-data" id="toc-q3.-admission-data" class="nav-link" data-scroll-target="#q3.-admission-data"><span class="toc-section-number">3</span>  Q3. <code>admission</code> data</a></li>
  <li><a href="#q4.-patients-data" id="toc-q4.-patients-data" class="nav-link" data-scroll-target="#q4.-patients-data"><span class="toc-section-number">4</span>  Q4. <code>patients</code> data</a></li>
  <li><a href="#q5.-lab-results" id="toc-q5.-lab-results" class="nav-link" data-scroll-target="#q5.-lab-results"><span class="toc-section-number">5</span>  Q5. Lab results</a></li>
  <li><a href="#q6.-vitals-from-charted-events" id="toc-q6.-vitals-from-charted-events" class="nav-link" data-scroll-target="#q6.-vitals-from-charted-events"><span class="toc-section-number">6</span>  Q6. Vitals from charted events</a></li>
  <li><a href="#q7.-putting-things-together" id="toc-q7.-putting-things-together" class="nav-link" data-scroll-target="#q7.-putting-things-together"><span class="toc-section-number">7</span>  Q7. Putting things together</a></li>
  <li><a href="#q8.-exploratory-data-analysis-eda" id="toc-q8.-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#q8.-exploratory-data-analysis-eda"><span class="toc-section-number">8</span>  Q8. Exploratory data analysis (EDA)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 203B Homework 2</h1>
<p class="subtitle lead">Due Feb 10 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hazel 005946282 </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<hr>
<p>Display machine information for reproducibility: ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>Load necessary libraries (you can add more as needed). ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(R.utils)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>MIMIC data location ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mimic_path <span class="ot">&lt;-</span> <span class="st">"~/mimic"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>In this exercise, we use tidyverse (ggplot2, dplyr, etc) to explore the <a href="https://mimic.mit.edu/docs/iv/">MIMIC-IV</a> data introduced in <a href="https://ucla-biostat-203b.github.io/2023winter/hw/hw1/hw1.html">homework 1</a> and to build a cohort of ICU stays.</p>
<p>Display the contents of MIMIC data folder. ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "total 24"                                                                
[2] "-rw-rw-r--@  1 huxuyi  staff  2518 Mar 10  2021 LICENSE.txt"             
[3] "drwxr-xr-x@  5 huxuyi  staff   160 Jan 20 21:09 MIMIC-reduce-chartevents"
[4] "-rw-rw-r--@  1 huxuyi  staff  2459 Mar 16  2021 SHA256SUMS.txt"          
[5] "drwxr-xr-x@  6 huxuyi  staff   192 Jan 20 21:08 core"                    
[6] "drwxr-xr-x@ 21 huxuyi  staff   672 Jan 20 21:08 hosp"                    
[7] "lrwxr-xr-x   1 huxuyi  staff    13 Jan 20 21:33 huxuyi -&gt; /Users/huxuyi" 
[8] "drwxr-xr-x@ 11 huxuyi  staff   352 Jan 20 21:09 icu"                     
[9] "-rw-rw-r--@  1 huxuyi  staff   797 Jan  4  2022 index.html"              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/core"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "total 142944"                                                        
[2] "-rw-rw-r--@ 1 huxuyi  staff  17208966 Mar 15  2021 admissions.csv.gz"
[3] "-rw-rw-r--@ 1 huxuyi  staff       606 Jan  4  2022 index.html"       
[4] "-rw-rw-r--@ 1 huxuyi  staff   2955582 Mar 15  2021 patients.csv.gz"  
[5] "-rw-rw-r--@ 1 huxuyi  staff  53014503 Mar 15  2021 transfers.csv.gz" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/hosp"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "total 9243184"                                                                        
 [2] "-rw-rw-r--@ 1 huxuyi  staff      430049 Mar 15  2021 d_hcpcs.csv.gz"                  
 [3] "-rw-rw-r--@ 1 huxuyi  staff      863239 Mar 15  2021 d_icd_diagnoses.csv.gz"          
 [4] "-rw-rw-r--@ 1 huxuyi  staff      579998 Mar 15  2021 d_icd_procedures.csv.gz"         
 [5] "-rw-rw-r--@ 1 huxuyi  staff       14898 Mar 15  2021 d_labitems.csv.gz"               
 [6] "-rw-rw-r--@ 1 huxuyi  staff    29531152 Mar 15  2021 diagnoses_icd.csv.gz"            
 [7] "-rw-rw-r--@ 1 huxuyi  staff    11684062 Mar 15  2021 drgcodes.csv.gz"                 
 [8] "-rw-rw-r--@ 1 huxuyi  staff   515763427 Mar 15  2021 emar.csv.gz"                     
 [9] "-rw-rw-r--@ 1 huxuyi  staff   476252563 Mar 15  2021 emar_detail.csv.gz"              
[10] "-rw-rw-r--@ 1 huxuyi  staff     2098831 Mar 15  2021 hcpcsevents.csv.gz"              
[11] "-rw-rw-r--@ 1 huxuyi  staff        2325 Jan  4  2022 index.html"                      
[12] "-rw-rw-r--@ 1 huxuyi  staff  2091865786 Mar 15  2021 labevents.csv.gz"                
[13] "-rw-rw-r--@ 1 huxuyi  staff   171624288 Jan 27  2022 labevents_filtered_itemid.csv.gz"
[14] "-rw-rw-r--@ 1 huxuyi  staff    99133381 Mar 15  2021 microbiologyevents.csv.gz"       
[15] "-rw-rw-r--@ 1 huxuyi  staff   422874088 Mar 15  2021 pharmacy.csv.gz"                 
[16] "-rw-rw-r--@ 1 huxuyi  staff   501381155 Mar 15  2021 poe.csv.gz"                      
[17] "-rw-rw-r--@ 1 huxuyi  staff    24020923 Mar 15  2021 poe_detail.csv.gz"               
[18] "-rw-rw-r--@ 1 huxuyi  staff   367041717 Mar 15  2021 prescriptions.csv.gz"            
[19] "-rw-rw-r--@ 1 huxuyi  staff     7750325 Mar 15  2021 procedures_icd.csv.gz"           
[20] "-rw-rw-r--@ 1 huxuyi  staff     9565293 Mar 15  2021 services.csv.gz"                 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/icu"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "total 5698008"                                                                          
 [2] "-rw-rw-r--@ 1 huxuyi  staff  2350783547 Mar 15  2021 chartevents.csv.gz"                
 [3] "-rw-rw-r--@ 1 huxuyi  staff   110272408 Jan 27  2022 chartevents_filtered_itemid.csv.gz"
 [4] "-rw-rw-r--@ 1 huxuyi  staff       55917 Mar 15  2021 d_items.csv.gz"                    
 [5] "-rw-rw-r--@ 1 huxuyi  staff    43296273 Mar 15  2021 datetimeevents.csv.gz"             
 [6] "-rw-rw-r--@ 1 huxuyi  staff     2848628 Mar 15  2021 icustays.csv.gz"                   
 [7] "-rw-rw-r--@ 1 huxuyi  staff        1103 Jan  4  2022 index.html"                        
 [8] "-rw-rw-r--@ 1 huxuyi  staff   352443512 Mar 15  2021 inputevents.csv.gz"                
 [9] "-rw-rw-r--@ 1 huxuyi  staff    37095672 Mar 15  2021 outputevents.csv.gz"               
[10] "-rw-rw-r--@ 1 huxuyi  staff    20567368 Mar 15  2021 procedureevents.csv.gz"            </code></pre>
</div>
<p>:::</p>
<section id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="header-section-number">1</span> Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</h2>
<p>There are quite a few utilities in R for reading plain text data files. Let us test the speed of reading a moderate sized compressed csv file, <code>admissions.csv.gz</code>, by three programs: <code>read.csv</code> in base R, <code>read_csv</code> in tidyverse, and <code>fread</code> in the popular data.table package.</p>
<p>Which function is fastest? Is there difference in the (default) parsed data types? (Hint: R function <code>system.time</code> measures run times.)</p>
<p>For later questions, we stick to the <code>read_csv</code> in tidyverse.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(data1<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"/Users/huxuyi/mimic/core/admissions.csv.gz"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
 12.941   0.303  13.340 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(data2<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"/Users/huxuyi/mimic/core/admissions.csv.gz"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  3.113   0.783   1.505 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(data3<span class="ot">&lt;-</span><span class="fu">fread</span>(<span class="st">"/Users/huxuyi/mimic/core/admissions.csv.gz"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  1.027   0.364   1.409 </code></pre>
</div>
</div>
<p><em>So, according to the results, ‘fread’ is the fastest.</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   523740 obs. of  15 variables:
 $ subject_id          : int  14679932 15585972 11989120 17817079 15078341 19124609 17301855 17991012 16865435 13693648 ...
 $ hadm_id             : int  21038362 24941086 21965160 24709883 23272159 20517215 29732723 24298836 23216961 21640725 ...
 $ admittime           : chr  "2139-09-26 14:16:00" "2123-10-07 23:56:00" "2147-01-14 09:00:00" "2165-12-27 17:33:00" ...
 $ dischtime           : chr  "2139-09-28 11:30:00" "2123-10-12 11:22:00" "2147-01-17 14:25:00" "2165-12-31 21:18:00" ...
 $ deathtime           : chr  "" "" "" "" ...
 $ admission_type      : chr  "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr  "" "" "" "" ...
 $ discharge_location  : chr  "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr  "Other" "Other" "Other" "Other" ...
 $ language            : chr  "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr  "SINGLE" "" "" "" ...
 $ ethnicity           : chr  "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : chr  "" "" "" "" ...
 $ edouttime           : chr  "" "" "" "" ...
 $ hospital_expire_flag: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [523,740 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ subject_id          : num [1:523740] 14679932 15585972 11989120 17817079 15078341 ...
 $ hadm_id             : num [1:523740] 21038362 24941086 21965160 24709883 23272159 ...
 $ admittime           : POSIXct[1:523740], format: "2139-09-26 14:16:00" "2123-10-07 23:56:00" ...
 $ dischtime           : POSIXct[1:523740], format: "2139-09-28 11:30:00" "2123-10-12 11:22:00" ...
 $ deathtime           : POSIXct[1:523740], format: NA NA ...
 $ admission_type      : chr [1:523740] "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr [1:523740] NA NA NA NA ...
 $ discharge_location  : chr [1:523740] "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr [1:523740] "Other" "Other" "Other" "Other" ...
 $ language            : chr [1:523740] "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr [1:523740] "SINGLE" NA NA NA ...
 $ ethnicity           : chr [1:523740] "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : POSIXct[1:523740], format: NA NA ...
 $ edouttime           : POSIXct[1:523740], format: NA NA ...
 $ hospital_expire_flag: num [1:523740] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   subject_id = col_double(),
  ..   hadm_id = col_double(),
  ..   admittime = col_datetime(format = ""),
  ..   dischtime = col_datetime(format = ""),
  ..   deathtime = col_datetime(format = ""),
  ..   admission_type = col_character(),
  ..   admission_location = col_character(),
  ..   discharge_location = col_character(),
  ..   insurance = col_character(),
  ..   language = col_character(),
  ..   marital_status = col_character(),
  ..   ethnicity = col_character(),
  ..   edregtime = col_datetime(format = ""),
  ..   edouttime = col_datetime(format = ""),
  ..   hospital_expire_flag = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  523740 obs. of  15 variables:
 $ subject_id          : int  14679932 15585972 11989120 17817079 15078341 19124609 17301855 17991012 16865435 13693648 ...
 $ hadm_id             : int  21038362 24941086 21965160 24709883 23272159 20517215 29732723 24298836 23216961 21640725 ...
 $ admittime           : POSIXct, format: "2139-09-26 14:16:00" "2123-10-07 23:56:00" ...
 $ dischtime           : POSIXct, format: "2139-09-28 11:30:00" "2123-10-12 11:22:00" ...
 $ deathtime           : POSIXct, format: NA NA ...
 $ admission_type      : chr  "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr  "" "" "" "" ...
 $ discharge_location  : chr  "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr  "Other" "Other" "Other" "Other" ...
 $ language            : chr  "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr  "SINGLE" "" "" "" ...
 $ ethnicity           : chr  "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : POSIXct, format: NA NA ...
 $ edouttime           : POSIXct, format: NA NA ...
 $ hospital_expire_flag: int  0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p><em>So, read.csv can not read datetime but read_csv and fread can.</em></p>
</section>
<section id="q2.-icu-stays" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="q2.-icu-stays"><span class="header-section-number">2</span> Q2. ICU stays</h2>
<p><code>icustays.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/icustays/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/icustays/</a>) contains data about Intensive Care Units (ICU) stays. The first 10 lines are ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"gzcat &lt; "</span>, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>), </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los"                                                    
 [2] "17867402,24528534,31793211,Trauma SICU (TSICU),Trauma SICU (TSICU),2154-03-03 04:11:00,2154-03-04 18:16:56,1.5874537037037035" 
 [3] "14435996,28960964,31983544,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-19 17:57:00,2150-06-22 18:33:54,3.025625"           
 [4] "17609946,27385897,33183475,Trauma SICU (TSICU),Trauma SICU (TSICU),2138-02-05 18:54:00,2138-02-15 12:42:05,9.741724537037038"  
 [5] "18966770,23483021,34131444,Trauma SICU (TSICU),Trauma SICU (TSICU),2123-10-25 10:35:00,2123-10-25 18:59:47,0.35054398148148147"
 [6] "12776735,20817525,34547665,Neuro Stepdown,Neuro Stepdown,2200-07-12 00:33:00,2200-07-13 16:44:40,1.6747685185185184"           
 [7] "10215159,24283593,34569476,Trauma SICU (TSICU),Trauma SICU (TSICU),2124-09-20 15:05:29,2124-09-21 22:06:58,1.2926967592592593" 
 [8] "14489052,26516390,35056286,Trauma SICU (TSICU),Trauma SICU (TSICU),2118-10-26 10:33:56,2118-10-26 20:28:10,0.4126620370370371" 
 [9] "15914763,28906020,36909804,Trauma SICU (TSICU),Trauma SICU (TSICU),2176-12-14 12:00:00,2176-12-17 11:47:01,2.9909837962962964" 
[10] "16256226,20013290,39289362,Neuro Stepdown,Neuro Stepdown,2150-12-20 16:09:08,2150-12-21 14:58:40,0.9510648148148149"           </code></pre>
</div>
<p>:::</p>
<ol type="1">
<li>Import <code>icustatys.csv.gz</code> as a tibble <code>icustays_tble</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>How many unique <code>subject_id</code>? Can a <code>subject_id</code> have multiple ICU stays?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(icustays_tble<span class="sc">$</span>subject_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53150</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(icustays_tble<span class="sc">$</span>stay_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76540</code></pre>
</div>
</div>
<p>53150 unique subject_id. Yes, since there are more stay_ids than subject_ids.</p>
<ol start="3" type="1">
<li>Summarize the number of ICU stays per <code>subject_id</code> by graphs.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>freq<span class="ot">&lt;-</span>icustays_tble[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">stays=</span><span class="fu">n</span>())</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>freq) <span class="sc">+</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_freqpoly</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>stays)) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Freqrency plot of the number of ICU stays per 'subject_id'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>For each <code>subject_id</code>, let’s only keep the first ICU stay in the tibble <code>icustays_tble</code>. (Hint: <code>slice_min</code> and <code>slice_max</code> may take long. Think alternative ways to achieve the same function.)</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>icustays_tble<span class="ot">&lt;-</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  icustays_tble <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(intime) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 8
   subject_id  hadm_id  stay_id first_careunit                                  
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                           
 1   10000032 29079034 39553978 Medical Intensive Care Unit (MICU)              
 2   10000980 26913865 39765666 Medical Intensive Care Unit (MICU)              
 3   10001217 24597018 37067082 Surgical Intensive Care Unit (SICU)             
 4   10001725 25563031 31205490 Medical/Surgical Intensive Care Unit (MICU/SICU)
 5   10001884 26184834 37510196 Medical Intensive Care Unit (MICU)              
 6   10002013 23581541 39060235 Cardiac Vascular Intensive Care Unit (CVICU)    
 7   10002155 23822395 33685454 Coronary Care Unit (CCU)                        
 8   10002223 22494570 39638202 Trauma SICU (TSICU)                             
 9   10002348 22725460 32610785 Neuro Intermediate                              
10   10002428 28662225 33987268 Medical Intensive Care Unit (MICU)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (MICU)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (MICU)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (SICU)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (MICU/SICU) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (MICU)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (CVICU)     2160-05-18 10:00:53
 7 Coronary Care Unit (CCU)                         2129-08-04 12:45:00
 8 Trauma SICU (TSICU)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (MICU)               2156-04-12 16:24:18
   outtime               los
   &lt;dttm&gt;              &lt;dbl&gt;
 1 2180-07-23 23:50:47 0.410
 2 2189-06-27 20:38:27 0.498
 3 2157-11-21 22:08:00 1.12 
 4 2110-04-12 23:59:56 1.34 
 5 2131-01-20 08:27:30 9.17 
 6 2160-05-19 17:33:33 1.31 
 7 2129-08-10 17:02:38 6.18 
 8 2158-01-16 15:19:24 1.30 
 9 2112-12-10 18:25:13 9.79 
10 2156-04-17 15:57:08 4.98 
# … with 53,140 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first_icu&lt;-icustays_tble%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   arrange(intime) %&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   distinct() %&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   print(width=Inf)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q3.-admission-data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="q3.-admission-data"><span class="header-section-number">3</span> Q3. <code>admission</code> data</h2>
<p>Information of the patients admitted into hospital is available in <code>admissions.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/hosp/admissions/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/admissions/</a> for details of each field in this file. The first 10 lines are ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/admissions.csv.gz"</span>), </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag"
 [2] "14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0"                                                                                
 [3] "15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [4] "11989120,21965160,2147-01-14 09:00:00,2147-01-17 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [5] "17817079,24709883,2165-12-27 17:33:00,2165-12-31 21:18:00,,ELECTIVE,,HOME,Other,ENGLISH,,OTHER,,,0"                                                                                        
 [6] "15078341,23272159,2122-08-28 08:48:00,2122-08-30 12:32:00,,ELECTIVE,,HOME,Other,ENGLISH,,BLACK/AFRICAN AMERICAN,,,0"                                                                       
 [7] "19124609,20517215,2169-03-14 12:44:00,2169-03-20 19:15:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [8] "17301855,29732723,2140-06-06 14:23:00,2140-06-08 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [9] "17991012,24298836,2181-07-10 20:28:00,2181-07-12 15:49:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
[10] "16865435,23216961,2185-07-19 02:12:00,2185-07-21 11:50:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        </code></pre>
</div>
<p>:::</p>
<ol type="1">
<li>Import <code>admissions.csv.gz</code> as a tibble <code>admissions_tble</code>. ::: {.cell layout-align=“center”}</li>
</ol>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>admissions_tble<span class="ot">&lt;-</span><span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">'/core/admissions.csv.gz'</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<ol start="2" type="1">
<li>Let’s only keep the admissions that have a match in <code>icustays_tble</code> according to <code>subject_id</code> and <code>hadmi_id</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">semi_join</span>(admissions_tble,icustays_tble,<span class="at">key=</span><span class="fu">c</span>(<span class="st">"subject_id"</span><span class="ot">=</span><span class="st">"subject_id"</span>,<span class="st">"hadmi_id"</span><span class="ot">=</span><span class="st">"hadmi_id"</span>)),<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 15
   subject_id  hadm_id admittime           dischtime          
        &lt;dbl&gt;    &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1   10222255 28200985 2120-11-20 20:25:00 2120-11-22 13:00:00
 2   14485852 28712010 2113-10-31 00:23:00 2113-11-04 16:50:00
 3   18709254 23758948 2195-10-12 01:31:00 2195-10-12 13:51:00
 4   16837807 23526268 2151-03-19 06:09:00 2151-03-19 07:20:00
 5   17642680 27734285 2116-05-29 12:48:00 2116-05-30 12:31:00
 6   18230965 21251728 2142-03-12 20:00:00 2142-03-17 15:26:00
 7   17374121 27667114 2115-07-22 07:15:00 2115-07-24 17:50:00
 8   13346506 28533404 2181-11-19 14:32:00 2181-11-22 18:47:00
 9   18030332 24679656 2152-07-22 21:28:00 2152-07-27 16:49:00
10   14328744 29576470 2126-08-20 09:26:00 2126-08-21 11:36:00
   deathtime           admission_type     admission_location    
   &lt;dttm&gt;              &lt;chr&gt;              &lt;chr&gt;                 
 1 NA                  EU OBSERVATION     TRANSFER FROM HOSPITAL
 2 NA                  EW EMER.           EMERGENCY ROOM        
 3 NA                  EU OBSERVATION     EMERGENCY ROOM        
 4 2151-03-19 07:20:00 EU OBSERVATION     EMERGENCY ROOM        
 5 NA                  EU OBSERVATION     WALK-IN/SELF REFERRAL 
 6 NA                  URGENT             PHYSICIAN REFERRAL    
 7 NA                  DIRECT OBSERVATION PHYSICIAN REFERRAL    
 8 NA                  EU OBSERVATION     EMERGENCY ROOM        
 9 NA                  URGENT             TRANSFER FROM HOSPITAL
10 NA                  EU OBSERVATION     EMERGENCY ROOM        
   discharge_location insurance language marital_status ethnicity
   &lt;chr&gt;              &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;          &lt;chr&gt;    
 1 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 2 &lt;NA&gt;               Other     ENGLISH  SINGLE         WHITE    
 3 &lt;NA&gt;               Medicaid  ENGLISH  WIDOWED        ASIAN    
 4 &lt;NA&gt;               Medicare  ENGLISH  SINGLE         WHITE    
 5 &lt;NA&gt;               Other     ENGLISH  SINGLE         WHITE    
 6 HOME               Other     ENGLISH  MARRIED        WHITE    
 7 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 8 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 9 HOME               Other     ENGLISH  MARRIED        UNKNOWN  
10 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
   edregtime           edouttime           hospital_expire_flag
   &lt;dttm&gt;              &lt;dttm&gt;                             &lt;dbl&gt;
 1 2120-11-20 18:07:00 2120-11-21 20:25:00                    0
 2 2113-10-30 19:48:00 2113-10-31 05:10:00                    0
 3 2195-10-11 18:40:00 2195-10-12 02:47:00                    0
 4 2151-03-19 02:55:00 2151-03-19 06:59:00                    1
 5 2116-05-29 10:05:00 2116-05-30 01:17:00                    0
 6 NA                  NA                                     0
 7 NA                  NA                                     0
 8 2181-11-19 10:51:00 2181-11-19 15:12:00                    0
 9 NA                  NA                                     0
10 2126-08-19 23:01:00 2126-08-20 10:14:00                    0
# … with 53,140 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li><p>Summarize the following variables by graphics.</p>
<ul>
<li>admission year<br>
</li>
<li>admission month<br>
</li>
<li>admission month day<br>
</li>
<li>admission week day<br>
</li>
<li>admission hour (anything unusual?)<br>
</li>
<li>admission minute (anything unusual?)<br>
</li>
<li>length of hospital stay (anything unusual?)</li>
</ul></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>adm_time<span class="ot">&lt;-</span><span class="fu">bind_cols</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">adm_year=</span><span class="fu">year</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">adm_month=</span><span class="fu">month</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">admi_md=</span><span class="fu">mday</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">admi_wd=</span><span class="fu">wday</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">admi_h=</span><span class="fu">hour</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">admi_ms=</span><span class="fu">minute</span>(admissions_tble<span class="sc">$</span>admittime),</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">stay=</span><span class="fu">difftime</span>(admissions_tble<span class="sc">$</span>dischtime,admissions_tble<span class="sc">$</span>admittime,<span class="at">units=</span><span class="fu">c</span>(<span class="st">'days'</span>))</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>admission year: ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_freqpoly</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>adm_year))<span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Year"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients in the admission year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>:::</p>
<p>-admission month: ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>adm_month))<span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Month"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients in the each month"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>::: There is no special pattern of patients’ admission observed by month. There are constant patients every month.</p>
<p>-admission month day: ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>admi_md))<span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Month Day"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients in the admission year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>::: There is no special pattern of patients’ admission observed by month. There are constant patients every month except for the end of two days of a month.</p>
<ul>
<li>admission week day: ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>admi_wd)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Week Day"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients in the each weekday"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>::: There is no special pattern of patients’ admission observed by day. There are constant patients every day.</p>
<ul>
<li>Admission hour: ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>admi_h))<span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Hour"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients in a day"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>:::</p>
<p>We could find that about the period of parents’ admission is about 6-8 hours. From 0-24, first the number of patients will decrease then increase in the morning at 7 am, and gradually increase until 6 pm, then it will decrease.</p>
<p>-admission minutes: ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>admi_ms))<span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Admission Minutes"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The number of patients with unit minutes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>:::</p>
<p>Patients come every about 15 minutes. The most people is at the beginning of a hour.</p>
<p>-Length of hospital stay ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>adm_time)<span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>stay))<span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Length of hospital stay"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The distribution of length of hospital stay of patients"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>df1<span class="ot">&lt;-</span><span class="fu">filter</span>(adm_time,stay<span class="sc">&lt;</span><span class="fu">quantile</span>(stay,<span class="fl">0.99</span>))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>df1<span class="ot">&lt;-</span><span class="fu">filter</span>(adm_time,stay<span class="sc">&lt;</span><span class="fu">quantile</span>(stay,<span class="fl">0.99</span>))</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>df1)<span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>stay))<span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Length of hospital stay"</span>,<span class="at">y=</span><span class="st">"Count"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The distribution of length of hospital stay of patients"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>df1)<span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>stay))<span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Length of hospital stay"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The distribution of length of hospital stay of patients"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>::: There are some extremely large outliers and the length of hospital stay seemed to be exponential distribution.</p>
</section>
<section id="q4.-patients-data" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="q4.-patients-data"><span class="header-section-number">4</span> Q4. <code>patients</code> data</h2>
<p>Patient information is available in <code>patients.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/hosp/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/patients/</a> for details of each field in this file. The first 10 lines are ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>), </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod"
 [2] "10000048,F,23,2126,2008 - 2010,"                               
 [3] "10002723,F,0,2128,2017 - 2019,"                                
 [4] "10003939,M,0,2184,2008 - 2010,"                                
 [5] "10004222,M,0,2161,2014 - 2016,"                                
 [6] "10005325,F,0,2154,2011 - 2013,"                                
 [7] "10007338,F,0,2153,2017 - 2019,"                                
 [8] "10008101,M,0,2142,2008 - 2010,"                                
 [9] "10009872,F,0,2168,2014 - 2016,"                                
[10] "10011333,F,0,2132,2014 - 2016,"                                </code></pre>
</div>
<p>:::</p>
<ol type="1">
<li>Import <code>patients.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/hosp/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/patients/</a>) as a tibble <code>patients_tble</code> and only keep the patients who have a match in <code>icustays_tble</code> (according to <code>subject_id</code>).</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="ot">&lt;-</span><span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Summarize variables <code>gender</code> and <code>anchor_age</code>, and explain any patterns you see.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df2<span class="ot">&lt;-</span>patients_tble <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender,anchor_age) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">counts=</span><span class="fu">n</span>())</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>df2<span class="ot">&lt;-</span><span class="fu">filter</span>(df2,anchor_age<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2) <span class="sc">+</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>anchor_age,<span class="at">y=</span>counts)) <span class="sc">+</span> </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">cols=</span><span class="fu">vars</span>(gender))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2)<span class="sc">+</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>anchor_age,<span class="at">y=</span>counts,<span class="at">group=</span>gender)) <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Length of hospital stay"</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"The distribution of length of hospital stay of patients"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Both female and male have the same pattern of the anchor_age: both has the most people aged 20, and fewest people aged about 84, and after 20 years old, the number of patients are decreasing. However, there are overall more female patients.</p>
</section>
<section id="q5.-lab-results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="q5.-lab-results"><span class="header-section-number">5</span> Q5. Lab results</h2>
<p><code>labevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/hosp/labevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/labevents/</a>) contains all laboratory measurements for patients. The first 10 lines are ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>), </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "labevent_id,subject_id,hadm_id,specimen_id,itemid,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments"
 [2] "670,10000048,,6448755,51484,2126-11-22 19:20:00,2126-11-22 20:07:00,150,150,mg/dL,,,,STAT,"                                                          
 [3] "673,10000048,,6448755,51491,2126-11-22 19:20:00,2126-11-22 20:07:00,6.5,6.5,units,5,8,,STAT,"                                                        
 [4] "675,10000048,,6448755,51498,2126-11-22 19:20:00,2126-11-22 20:07:00,1.029,1.029, ,1.001,1.035,,STAT,"                                                
 [5] "683,10000048,,82729055,50861,2126-11-22 20:45:00,2126-11-23 00:55:00,39,39,IU/L,0,40,,STAT,"                                                         
 [6] "684,10000048,,82729055,50862,2126-11-22 20:45:00,2126-11-23 00:55:00,4.7,4.7,g/dL,3.4,4.8,,STAT,"                                                    
 [7] "685,10000048,,82729055,50863,2126-11-22 20:45:00,2126-11-23 00:55:00,45,45,IU/L,39,117,,STAT,"                                                       
 [8] "686,10000048,,82729055,50868,2126-11-22 20:45:00,2126-11-22 21:32:00,13,13,mEq/L,8,20,,STAT,"                                                        
 [9] "687,10000048,,82729055,50878,2126-11-22 20:45:00,2126-11-23 00:55:00,28,28,IU/L,0,40,,STAT,"                                                         
[10] "688,10000048,,82729055,50882,2126-11-22 20:45:00,2126-11-22 21:32:00,26,26,mEq/L,22,32,,STAT,"                                                       </code></pre>
</div>
<p>::: <code>d_labitems.csv.gz</code> is the dictionary of lab measurements. ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/d_labitems.csv.gz"</span>), </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,fluid,category,loinc_code"           
 [2] "51905, ,Other Body Fluid,Chemistry,"              
 [3] "51532,11-Deoxycorticosterone,Blood,Chemistry,"    
 [4] "51957,17-Hydroxycorticosteroids,Urine,Chemistry," 
 [5] "51958,\"17-Ketosteroids, Urine\",Urine,Chemistry,"
 [6] "52068,24 Hr,Blood,Hematology,"                    
 [7] "51066,24 hr Calcium,Urine,Chemistry,"             
 [8] "51067,24 hr Creatinine,Urine,Chemistry,"          
 [9] "51068,24 hr Protein,Urine,Chemistry,"             
[10] "50853,25-OH Vitamin D,Blood,Chemistry,"           </code></pre>
</div>
<p>:::</p>
<ol type="1">
<li>Find how many rows are in <code>labevents.csv.gz</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>), </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | wc -l"</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>122103667 Lines. (wc -l will contains a built-in switch, -n, to remove newline)</p>
<ol start="2" type="1">
<li><p>We are interested in the lab measurements of creatinine (50912), potassium (50971), sodium (50983), chloride (50902), bicarbonate (50882), hematocrit (51221), white blood cell count (51301), and glucose (50931). Retrieve a subset of <code>labevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>labevents_tble</code>.</p>
<p>Hint: <code>labevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer 5-10 minutes to ingest this file. If your computer really has trouble importing <code>labevents.csv.gz</code>, you can import from the reduced data file <code>labevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>icustays_tble0<span class="ot">&lt;-</span><span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">"/icu/icustays.csv.gz"</span>)))</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>labevents_tble0<span class="ot">&lt;-</span><span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">"/hosp/labevents_filtered_itemid.csv.gz"</span>)),<span class="at">lazy=</span>T,<span class="at">delim=</span><span class="st">','</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">&lt;-</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(labevents_tble0,icustays_tble0,<span class="at">by=</span><span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">50912</span>,<span class="dv">50971</span>,<span class="dv">50983</span>,<span class="dv">50902</span>,<span class="dv">50882</span>,<span class="dv">51221</span>,<span class="dv">51301</span>,<span class="dv">50931</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13,926,853 × 4
   subject_id itemid charttime           valuenum
        &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;                 &lt;dbl&gt;
 1   10003700  50882 2162-11-15 17:00:00     27  
 2   10003700  50902 2162-11-15 17:00:00    103  
 3   10003700  50912 2162-11-15 17:00:00      1  
 4   10003700  50931 2162-11-15 17:00:00     93  
 5   10003700  50971 2162-11-15 17:00:00      4.1
 6   10003700  50983 2162-11-15 17:00:00    141  
 7   10003700  51221 2162-11-15 17:00:00     40  
 8   10003700  51301 2162-11-15 17:00:00      6.7
 9   10003700  51221 2165-04-24 03:40:00     41  
10   10003700  51301 2165-04-24 03:40:00      5.8
# … with 13,926,843 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Further restrict <code>labevents_tble</code> to the first lab measurement during the ICU stay. ::: {.cell layout-align=“center”}</li>
</ol>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>labevents_tble1<span class="ot">&lt;-</span>labevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(icustays_tble0, subject_id, intime, outtime),<span class="at">by=</span><span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intime<span class="sc">&lt;=</span>charttime<span class="sc">&amp;</span>charttime<span class="sc">&lt;=</span>outtime) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id,itemid) <span class="sc">%&gt;%</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime,<span class="at">by_group=</span>T) <span class="sc">%&gt;%</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># important to take out before pivot_wider o/w multiple rows.</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>intime,<span class="sc">-</span>outtime,<span class="sc">-</span>charttime) <span class="sc">%&gt;%</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> itemid, <span class="at">values_from =</span> valuenum) <span class="sc">%&gt;%</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">'bicarbonate'</span><span class="ot">=</span><span class="st">'50882'</span>,<span class="st">'creatinine'</span><span class="ot">=</span><span class="st">'50912'</span>,<span class="st">'potassium'</span><span class="ot">=</span><span class="st">'50971'</span>,</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>         <span class="st">'sodium'</span><span class="ot">=</span><span class="st">'50983'</span>,<span class="st">'chloride'</span><span class="ot">=</span><span class="st">'50902'</span>,<span class="st">'hematocrit'</span><span class="ot">=</span><span class="st">'51221'</span>,<span class="st">'n_wb_cell'</span><span class="ot">=</span><span class="st">'51301'</span>,</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>         <span class="st">'glucose'</span><span class="ot">=</span><span class="st">'50931'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51,892 × 9
   subject_id bicarbonate chloride creatinine glucose potassium sodium
        &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
 1   10000032          21      102        0.5     115       4.7    132
 2   10001217          23      104        0.4     113       3.6    138
 3   10001725          24      106        0.8     146       3.9    140
 4   10001884          33       96        1.1     148       4      136
 5   10002013          23      109        1.1      98       4      140
 6   10002155          25      106        0.9      95       4.5    139
 7   10002223          26      102        0.8      88       3.9    138
 8   10002348          23      107        0.8     127       4.8    142
 9   10002428          20       98        0.8      99       3.9    129
10   10002430          22      105        2.2     128       3.8    144
   hematocrit n_wb_cell
        &lt;dbl&gt;     &lt;dbl&gt;
 1       NA        NA  
 2       33.6      19  
 3       39.1      17  
 4       36        18.4
 5       28.6      18.2
 6       37.9       5.5
 7       32.5      10.1
 8       39.3       4.3
 9       28.7      22.4
10       36.6      10.3
# … with 51,882 more rows</code></pre>
</div>
<p>:::</p>
<ol start="4" type="1">
<li>Summarize the lab measurements by appropriate numerics and graphics. ::: {.cell layout-align=“center”}</li>
</ol>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(labevents_tble1[,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bicarbonate       chloride       creatinine        glucose      
 Min.   : 2.00   Min.   : 58.0   Min.   : 0.000   Min.   :   7.0  
 1st Qu.:21.00   1st Qu.:101.0   1st Qu.: 0.700   1st Qu.: 103.0  
 Median :23.00   Median :105.0   Median : 0.900   Median : 124.0  
 Mean   :22.97   Mean   :104.5   Mean   : 1.312   Mean   : 141.4  
 3rd Qu.:25.00   3rd Qu.:108.0   3rd Qu.: 1.300   3rd Qu.: 156.0  
 Max.   :49.00   Max.   :153.0   Max.   :36.900   Max.   :2440.0  
 NA's   :226     NA's   :191     NA's   :205      NA's   :287     
   potassium          sodium        hematocrit      n_wb_cell     
 Min.   : 0.800   Min.   : 92.0   Min.   : 4.30   Min.   :  0.00  
 1st Qu.: 3.700   1st Qu.:136.0   1st Qu.:28.10   1st Qu.:  7.60  
 Median : 4.100   Median :139.0   Median :32.60   Median : 10.50  
 Mean   : 4.178   Mean   :138.5   Mean   :32.74   Mean   : 12.07  
 3rd Qu.: 4.500   3rd Qu.:141.0   3rd Qu.:37.30   3rd Qu.: 14.50  
 Max.   :13.000   Max.   :180.0   Max.   :68.60   Max.   :572.50  
 NA's   :217      NA's   :184     NA's   :427     NA's   :522     </code></pre>
</div>
<p>:::</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>labevents_tble1[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">&amp;</span> value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="co">#delete the outliers</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">y=</span>value)) <span class="sc">+</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free_y'</span>,<span class="at">nrow=</span><span class="dv">3</span>,<span class="at">ncol=</span><span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>labevents_tble1[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">&amp;</span> value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free'</span>,<span class="at">nrow=</span><span class="dv">3</span>,<span class="at">ncol=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Due to the influence of outliers, the boxplots seems to be weird, so, we need to filter some outliers. From the boxplots and histograms, we could know that the distribution of glucose, number of white blood cell and creatinine have a slight right skewness. hematocrit is pretty symmetric and comforms to normal distribution. Bicarbonate and chloride sodium and potassium have some gaps for their values.</p>
</section>
<section id="q6.-vitals-from-charted-events" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="q6.-vitals-from-charted-events"><span class="header-section-number">6</span> Q6. Vitals from charted events</h2>
<p><code>chartevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/chartevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/chartevents/</a>) contains all the charted data available for a patient. During their ICU stay, the primary repository of a patient’s information is their electronic chart. The <code>itemid</code> variable indicates a single measurement type in the database. The <code>value</code> variable is the value measured for <code>itemid</code>. The first 10 lines of <code>chartevents.csv.gz</code> are ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/chartevents.csv.gz"</span>), </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,charttime,storetime,itemid,value,valuenum,valueuom,warning"
 [2] "10003700,28623837,30600691,2165-04-24 05:10:00,2165-04-24 05:11:00,228236,0,0,,0"     
 [3] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225067,0,0,,0"     
 [4] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225070,1,1,,0"     
 [5] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225076,1,1,,0"     
 [6] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225078,1,1,,0"     
 [7] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225086,1,1,,0"     
 [8] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225091,1,1,,0"     
 [9] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225103,1,1,,0"     
[10] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225106,1,1,,0"     </code></pre>
</div>
<p>:::</p>
<p><code>d_items.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/d_items/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/d_items/</a>) is the dictionary for the <code>itemid</code> in <code>chartevents.csv.gz</code>. ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/d_items.csv.gz"</span>), </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue"   
 [2] "220003,ICU Admission date,ICU Admission date,datetimeevents,ADT,,Date and time,,"                
 [3] "220045,Heart Rate,HR,chartevents,Routine Vital Signs,bpm,Numeric,,"                              
 [4] "220046,Heart rate Alarm - High,HR Alarm - High,chartevents,Alarms,bpm,Numeric,,"                 
 [5] "220047,Heart Rate Alarm - Low,HR Alarm - Low,chartevents,Alarms,bpm,Numeric,,"                   
 [6] "220048,Heart Rhythm,Heart Rhythm,chartevents,Routine Vital Signs,,Text,,"                        
 [7] "220050,Arterial Blood Pressure systolic,ABPs,chartevents,Routine Vital Signs,mmHg,Numeric,90,140"
 [8] "220051,Arterial Blood Pressure diastolic,ABPd,chartevents,Routine Vital Signs,mmHg,Numeric,60,90"
 [9] "220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg,Numeric,,"         
[10] "220056,Arterial Blood Pressure Alarm - Low,ABP Alarm - Low,chartevents,Alarms,mmHg,Numeric,,"    </code></pre>
</div>
<p>:::</p>
<ol type="1">
<li><p>We are interested in the vitals for ICU patients: heart rate (220045), mean non-invasive blood pressure (220181), systolic non-invasive blood pressure (220179), body temperature in Fahrenheit (223761), and respiratory rate (220210). Retrieve a subset of <code>chartevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>chartevents_tble</code>.</p>
<p>Hint: <code>chartevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer &gt;15 minutes to ingest this file. If your computer really has trouble importing <code>chartevents.csv.gz</code>, you can import from the reduced data file <code>chartevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble0<span class="ot">&lt;-</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/chartevents_filtered_itemid.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble<span class="ot">&lt;-</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(chartevents_tble0,itemid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">220045</span>,<span class="dv">220181</span>,<span class="dv">220179</span>,<span class="dv">223761</span>,<span class="dv">220210</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(icustays_tble,<span class="at">by=</span><span class="st">'subject_id'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,679,058 × 6
   subject_id  hadm_id  stay_id charttime           itemid valuenum
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dttm&gt;               &lt;dbl&gt;    &lt;dbl&gt;
 1   10003700 28623837 30600691 2165-04-24 05:28:00 220179    152  
 2   10003700 28623837 30600691 2165-04-24 05:28:00 220181    110  
 3   10003700 28623837 30600691 2165-04-24 05:30:00 220045     65  
 4   10003700 28623837 30600691 2165-04-24 05:30:00 220210     14  
 5   10003700 28623837 30600691 2165-04-24 05:38:00 223761     97.6
 6   10003700 28623837 30600691 2165-04-24 06:00:00 220045     56  
 7   10003700 28623837 30600691 2165-04-24 06:00:00 220179    126  
 8   10003700 28623837 30600691 2165-04-24 06:00:00 220181     88  
 9   10003700 28623837 30600691 2165-04-24 06:00:00 220210     14  
10   10003700 28623837 30600691 2165-04-24 06:09:00 220045     55  
# … with 23,679,048 more rows</code></pre>
</div>
</div>
<p>heart rate (220045), mean non-invasive blood pressure (220181), systolic non-invasive blood pressure (220179), body temperature in Fahrenheit (223761), and respiratory rate (220210) 2. Further restrict <code>chartevents_tble</code> to the first vital measurement during the ICU stay.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble1 <span class="ot">&lt;-</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  chartevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(icustays_tble, subject_id, intime, outtime),<span class="at">by=</span><span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intime<span class="sc">&lt;=</span>charttime <span class="sc">&amp;</span> charttime<span class="sc">&lt;=</span>outtime) <span class="sc">%&gt;%</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id,itemid) <span class="sc">%&gt;%</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime,<span class="at">by_group=</span>T) <span class="sc">%&gt;%</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># important to take out before pivot_wider o/w multiple rows.</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>intime,<span class="sc">-</span>outtime,<span class="sc">-</span>charttime,<span class="sc">-</span>hadm_id,<span class="sc">-</span>stay_id) <span class="sc">%&gt;%</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> itemid, <span class="at">values_from =</span> valuenum) <span class="sc">%&gt;%</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">'heart_rate'</span><span class="ot">=</span><span class="st">'220045'</span>,<span class="st">'ni_blood_pressure'</span><span class="ot">=</span><span class="st">'220181'</span>,<span class="st">'sni_blood_pressure'</span><span class="ot">=</span><span class="st">'220179'</span>,<span class="st">'body_temp'</span><span class="ot">=</span><span class="st">'223761'</span>,<span class="st">'respiratory_rate'</span><span class="ot">=</span><span class="st">'220210'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,136 × 6
   subject_id heart_rate sni_blood_pressure ni_blood_pressure respiratory_rate
        &lt;dbl&gt;      &lt;dbl&gt;              &lt;dbl&gt;             &lt;dbl&gt;            &lt;dbl&gt;
 1   10000032         91                 84                56               24
 2   10000980         77                150                92               23
 3   10001217         86                151               104               18
 4   10001725         55                 73                59               19
 5   10001884         38                180                46               10
 6   10002013         80                104                77               14
 7   10002155         68                126                78               18
 8   10002223        100                123                80               29
 9   10002348         72                129                85               14
10   10002428        124                 87                53               25
   body_temp
       &lt;dbl&gt;
 1      98.7
 2      98  
 3      98.5
 4      97.7
 5      98.1
 6      97.2
 7      95.9
 8      98.6
 9      97.9
10     103. 
# … with 53,126 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Summarize these vital measurements by appropriate numerics and graphics.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chartevents_tble1[,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   heart_rate     sni_blood_pressure ni_blood_pressure   respiratory_rate
 Min.   :  0.00   Min.   :    0.0    Min.   :     0.00   Min.   :  0.00  
 1st Qu.: 74.00   1st Qu.:  106.0    1st Qu.:    70.00   1st Qu.: 15.00  
 Median : 85.00   Median :  122.0    Median :    81.00   Median : 18.00  
 Mean   : 87.47   Mean   :  123.8    Mean   :    87.42   Mean   : 18.69  
 3rd Qu.: 99.00   3rd Qu.:  139.0    3rd Qu.:    93.00   3rd Qu.: 22.00  
 Max.   :941.00   Max.   :12262.0    Max.   :140119.00   Max.   :180.00  
 NA's   :1        NA's   :669        NA's   :690         NA's   :48      
   body_temp     
 Min.   :  0.00  
 1st Qu.: 97.60  
 Median : 98.10  
 Mean   : 98.03  
 3rd Qu.: 98.70  
 Max.   :106.00  
 NA's   :940     </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble1[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">&amp;</span> value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="co">#delete the outliers</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">y=</span>value)) <span class="sc">+</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free_y'</span>,<span class="at">ncol=</span><span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble1[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">&amp;</span> value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free'</span>,<span class="at">nrow=</span><span class="dv">3</span>,<span class="at">ncol=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Due to the influence of outliers, the boxplots seems to be weird, so, we need to filter some outliers. From the boxplots and histograms, we could know that the distribution of heart rate,respiratory rate and mean non-invasive blood pressure have a slight right skewness. body temperature in Fahrenheit is pretty symmetric and comforms to normal distribution. respiratory rate has some gaps for their values.</p>
</section>
<section id="q7.-putting-things-together" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="q7.-putting-things-together"><span class="header-section-number">7</span> Q7. Putting things together</h2>
<p>Let us create a tibble <code>mimic_icu_cohort</code> for all ICU stays, where rows are the first ICU stay of each unique adult (age at admission &gt; 18) and columns contain at least following variables</p>
<ul>
<li>all variables in <code>icustays.csv.gz</code><br>
</li>
<li>all variables in <code>admission.csv.gz</code><br>
</li>
<li>all variables in <code>patients.csv.gz</code><br>
</li>
<li>first lab measurements during ICU stay<br>
</li>
<li>first vital measurements during ICU stay</li>
<li>an indicator variable <code>thirty_day_mort</code> whether the patient died within 30 days of hospital admission (30 day mortality)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>admissions_tble1<span class="ot">&lt;-</span><span class="fu">semi_join</span>(admissions_tble,icustays_tble,<span class="at">by=</span><span class="fu">c</span>(<span class="st">'subject_id'</span>,<span class="st">'hadm_id'</span>)) <span class="co">#keep only the first icu stay of each patient</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>patients_tble1<span class="ot">&lt;-</span><span class="fu">semi_join</span>(patients_tble,icustays_tble,<span class="at">by=</span><span class="st">'subject_id'</span>) <span class="co">#keep only the first icu stay of each patient</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co">#First combine all of 5 tables and then select age&gt;18, then create the thirty_day_mort variables</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="ot">&lt;-</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(icustays_tble,admissions_tble1,<span class="at">by=</span><span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(patients_tble,<span class="at">by=</span><span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(labevents_tble1,<span class="at">by=</span><span class="st">'subject_id'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(chartevents_tble1,<span class="at">by=</span><span class="st">'subject_id'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age=</span><span class="fu">year</span>(admittime)<span class="sc">-</span>anchor_year<span class="sc">+</span>anchor_age) <span class="sc">%&gt;%</span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age<span class="sc">&gt;</span><span class="dv">18</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">thirty_day_mort=</span><span class="fu">if_else</span>(<span class="fu">is.na</span>(deathtime),<span class="st">'No'</span>,                                                    <span class="fu">if_else</span>(<span class="fu">as.Date</span>(deathtime)<span class="sc">-</span><span class="fu">as.Date</span>(admittime)<span class="sc">&lt;=</span><span class="dv">30</span>,<span class="st">"Yes"</span>,<span class="st">"No"</span>)))  <span class="sc">%&gt;%</span></span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Yes -&gt; die No-&gt;alive</span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,065 × 42
   subject_id hadm_id.x  stay_id
        &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1   10000032  29079034 39553978
 2   10000980  26913865 39765666
 3   10001217  24597018 37067082
 4   10001725  25563031 31205490
 5   10001884  26184834 37510196
 6   10002013  23581541 39060235
 7   10002155  23822395 33685454
 8   10002223  22494570 39638202
 9   10002348  22725460 32610785
10   10002428  28662225 33987268
   first_careunit                                  
   &lt;chr&gt;                                           
 1 Medical Intensive Care Unit (MICU)              
 2 Medical Intensive Care Unit (MICU)              
 3 Surgical Intensive Care Unit (SICU)             
 4 Medical/Surgical Intensive Care Unit (MICU/SICU)
 5 Medical Intensive Care Unit (MICU)              
 6 Cardiac Vascular Intensive Care Unit (CVICU)    
 7 Coronary Care Unit (CCU)                        
 8 Trauma SICU (TSICU)                             
 9 Neuro Intermediate                              
10 Medical Intensive Care Unit (MICU)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (MICU)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (MICU)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (SICU)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (MICU/SICU) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (MICU)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (CVICU)     2160-05-18 10:00:53
 7 Coronary Care Unit (CCU)                         2129-08-04 12:45:00
 8 Trauma SICU (TSICU)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (MICU)               2156-04-12 16:24:18
   outtime               los hadm_id.y admittime           dischtime          
   &lt;dttm&gt;              &lt;dbl&gt;     &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1 2180-07-23 23:50:47 0.410  29079034 2180-07-23 12:35:00 2180-07-25 17:55:00
 2 2189-06-27 20:38:27 0.498  26913865 2189-06-27 07:38:00 2189-07-03 03:00:00
 3 2157-11-21 22:08:00 1.12   24597018 2157-11-18 22:56:00 2157-11-25 18:00:00
 4 2110-04-12 23:59:56 1.34   25563031 2110-04-11 15:08:00 2110-04-14 15:00:00
 5 2131-01-20 08:27:30 9.17   26184834 2131-01-07 20:39:00 2131-01-20 05:15:00
 6 2160-05-19 17:33:33 1.31   23581541 2160-05-18 07:45:00 2160-05-23 13:30:00
 7 2129-08-10 17:02:38 6.18   23822395 2129-08-04 12:44:00 2129-08-18 16:53:00
 8 2158-01-16 15:19:24 1.30   22494570 2158-01-15 08:00:00 2158-01-20 19:29:00
 9 2112-12-10 18:25:13 9.79   22725460 2112-11-30 22:22:00 2112-12-10 17:56:00
10 2156-04-17 15:57:08 4.98   28662225 2156-04-12 14:16:00 2156-04-29 16:26:00
   deathtime           admission_type              admission_location    
   &lt;dttm&gt;              &lt;chr&gt;                       &lt;chr&gt;                 
 1 NA                  EW EMER.                    EMERGENCY ROOM        
 2 NA                  EW EMER.                    EMERGENCY ROOM        
 3 NA                  EW EMER.                    EMERGENCY ROOM        
 4 NA                  EW EMER.                    PACU                  
 5 2131-01-20 05:15:00 OBSERVATION ADMIT           EMERGENCY ROOM        
 6 NA                  SURGICAL SAME DAY ADMISSION PHYSICIAN REFERRAL    
 7 NA                  EW EMER.                    PROCEDURE SITE        
 8 NA                  EW EMER.                    EMERGENCY ROOM        
 9 NA                  OBSERVATION ADMIT           TRANSFER FROM HOSPITAL
10 NA                  EW EMER.                    EMERGENCY ROOM        
   discharge_location           insurance language marital_status
   &lt;chr&gt;                        &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;         
 1 HOME                         Medicaid  ENGLISH  WIDOWED       
 2 HOME HEALTH CARE             Medicare  ENGLISH  MARRIED       
 3 HOME HEALTH CARE             Other     ?        MARRIED       
 4 HOME                         Other     ENGLISH  MARRIED       
 5 DIED                         Medicare  ENGLISH  MARRIED       
 6 HOME HEALTH CARE             Medicare  ENGLISH  SINGLE        
 7 CHRONIC/LONG TERM ACUTE CARE Other     ENGLISH  MARRIED       
 8 HOME                         Other     ENGLISH  &lt;NA&gt;          
 9 HOME HEALTH CARE             Medicare  ENGLISH  SINGLE        
10 SKILLED NURSING FACILITY     Medicare  ENGLISH  WIDOWED       
   ethnicity              edregtime           edouttime          
   &lt;chr&gt;                  &lt;dttm&gt;              &lt;dttm&gt;             
 1 WHITE                  2180-07-23 05:54:00 2180-07-23 14:00:00
 2 BLACK/AFRICAN AMERICAN 2189-06-27 06:25:00 2189-06-27 08:42:00
 3 WHITE                  2157-11-18 17:38:00 2157-11-19 01:24:00
 4 WHITE                  NA                  NA                 
 5 BLACK/AFRICAN AMERICAN 2131-01-07 13:36:00 2131-01-07 22:13:00
 6 OTHER                  NA                  NA                 
 7 WHITE                  2129-08-04 11:00:00 2129-08-04 12:35:00
 8 UNABLE TO OBTAIN       2158-01-15 06:49:00 2158-01-15 07:36:00
 9 WHITE                  2112-11-30 15:08:00 2112-11-30 23:24:00
10 WHITE                  2156-04-12 09:56:00 2156-04-12 17:11:00
   hospital_expire_flag gender anchor_age anchor_year anchor_year_group
                  &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;            
 1                    0 F              52        2180 2014 - 2016      
 2                    0 F              73        2186 2008 - 2010      
 3                    0 F              55        2157 2011 - 2013      
 4                    0 F              46        2110 2011 - 2013      
 5                    1 F              68        2122 2008 - 2010      
 6                    0 F              53        2156 2008 - 2010      
 7                    0 F              80        2128 2008 - 2010      
 8                    0 M              21        2158 2008 - 2010      
 9                    0 F              77        2112 2017 - 2019      
10                    0 F              80        2155 2011 - 2013      
   dod        bicarbonate chloride creatinine glucose potassium sodium
   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
 1 NA                  21      102        0.5     115       4.7    132
 2 NA                  NA       NA       NA        NA      NA       NA
 3 NA                  23      104        0.4     113       3.6    138
 4 NA                  24      106        0.8     146       3.9    140
 5 2131-01-20          33       96        1.1     148       4      136
 6 NA                  23      109        1.1      98       4      140
 7 2131-03-10          25      106        0.9      95       4.5    139
 8 NA                  26      102        0.8      88       3.9    138
 9 NA                  23      107        0.8     127       4.8    142
10 NA                  20       98        0.8      99       3.9    129
   hematocrit n_wb_cell heart_rate sni_blood_pressure ni_blood_pressure
        &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;              &lt;dbl&gt;             &lt;dbl&gt;
 1       NA        NA           91                 84                56
 2       NA        NA           77                150                92
 3       33.6      19           86                151               104
 4       39.1      17           55                 73                59
 5       36        18.4         38                180                46
 6       28.6      18.2         80                104                77
 7       37.9       5.5         68                126                78
 8       32.5      10.1        100                123                80
 9       39.3       4.3         72                129                85
10       28.7      22.4        124                 87                53
   respiratory_rate body_temp   age thirty_day_mort
              &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          
 1               24      98.7    52 No             
 2               23      98      76 No             
 3               18      98.5    55 No             
 4               19      97.7    46 No             
 5               10      98.1    77 Yes            
 6               14      97.2    57 No             
 7               18      95.9    81 No             
 8               29      98.6    21 No             
 9               14      97.9    77 No             
10               25     103.     81 No             
# … with 53,055 more rows</code></pre>
</div>
</div>
</section>
<section id="q8.-exploratory-data-analysis-eda" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="q8.-exploratory-data-analysis-eda"><span class="header-section-number">8</span> Q8. Exploratory data analysis (EDA)</h2>
<p>Summarize following information using appropriate numerics or graphs.</p>
<ul>
<li><code>thirty_day_mort</code> vs demographic variables ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#categorical data vs categorical data</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>categ<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">'thirty_day_mort'</span>,<span class="st">'gender'</span>,<span class="st">'language'</span>,<span class="st">'insurance'</span>,<span class="st">'marital_status'</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>op<span class="ot">=</span><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>){</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  a<span class="ot">&lt;-</span><span class="fu">table</span>(mimic_icu_cohort[[categ[<span class="dv">1</span>]]],mimic_icu_cohort[[categ[i]]]) </span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(a)</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">barplot</span>(a,<span class="at">cex.axis=</span><span class="dv">1</span>,<span class="at">cex.names=</span><span class="fl">0.5</span>,)</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
          F     M
  No  20901 26952
  Yes  2413  2799</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     
          ? ENGLISH
  No   4730   43123
  Yes   560    4652</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      Medicaid Medicare Other
  No      3532    20009 24312
  Yes      297     2767  2148</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      DIVORCED MARRIED SINGLE WIDOWED
  No      3399   22062  13170    5629
  Yes      296    2050   1001     841</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>par<span class="ot">=</span>op</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: 1. Gender: Gender has no association with the mortality rate during 30 days in ICU. 2. Language:Most people (about 90%) speak English. Language has no association with the mortality rate during 30 days in ICU. 3. Insurance: For people with medicare, the death rate is the highest during 30 days in ICU. 4. Martial status: For people who married, the death rate is the highest during 30 days in ICU, and then is the widowed people. Single people tend to the lowest death rate.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>thirty_day_mort,<span class="at">fill=</span>ethnicity),<span class="at">position =</span> <span class="st">'fill'</span>)<span class="sc">+</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">'30 days mortality vs ethnicity'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Ethnicity: For Hispanic, Black people and White people, survival rate is larger than motility rate in the first 30 days in ICU. It is almost equivalent for Asian and other.</li>
</ol>
<ul>
<li><code>thirty_day_mort</code> vs first lab measurements ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>lab_measure<span class="ot">&lt;-</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mimic_icu_cohort,<span class="fu">c</span>(<span class="st">'bicarbonate'</span>,<span class="st">'creatinine'</span>,<span class="st">'potassium'</span>,<span class="st">'sodium'</span>,</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'chloride'</span>,<span class="st">'hematocrit'</span>,<span class="st">"n_wb_cell"</span>,<span class="st">'glucose'</span>,</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'thirty_day_mort'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span>bicarbonate<span class="sc">:</span>glucose) <span class="sc">%&gt;%</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span>T) <span class="sc">&amp;</span> </span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>           value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span>T)) <span class="sc">%&gt;%</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary table</span></span>
<span id="cb91-13"><a href="#cb91-13" aria-hidden="true" tabindex="-1"></a>lab_measure <span class="sc">%&gt;%</span></span>
<span id="cb91-14"><a href="#cb91-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name,thirty_day_mort) <span class="sc">%&gt;%</span></span>
<span id="cb91-15"><a href="#cb91-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb91-16"><a href="#cb91-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean=</span><span class="fu">mean</span>(value),</span>
<span id="cb91-17"><a href="#cb91-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">min=</span><span class="fu">min</span>(value),</span>
<span id="cb91-18"><a href="#cb91-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">max=</span><span class="fu">max</span>(value),</span>
<span id="cb91-19"><a href="#cb91-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">median=</span><span class="fu">median</span>(value),</span>
<span id="cb91-20"><a href="#cb91-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">q25=</span><span class="fu">quantile</span>(value,<span class="fl">0.25</span>),</span>
<span id="cb91-21"><a href="#cb91-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">q75=</span><span class="fu">quantile</span>(value,<span class="fl">0.75</span>),</span>
<span id="cb91-22"><a href="#cb91-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">variance=</span><span class="fu">var</span>(value)</span>
<span id="cb91-23"><a href="#cb91-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb91-24"><a href="#cb91-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 9
# Groups:   name [8]
   name        thirty_day_mort   mean   min   max median   q25   q75 variance
   &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 bicarbonate No               23.1   13.5  31     23    21    25     11.2  
 2 bicarbonate Yes              21.6   14    31.8   21    18    24     16.4  
 3 chloride    No              105.    92   115    105   102   108     23.7  
 4 chloride    Yes             104.    92   115    104   100   108     30.9  
 5 creatinine  No                1.11   0.5   5.2    0.9   0.7   1.2    0.484
 6 creatinine  Yes               1.61   0.5   5.2    1.3   0.9   2      1.03 
 7 glucose     No              134.    75   318    123   104   151   1909.   
 8 glucose     Yes             151.    75   318    139   110   180   2915.   
 9 hematocrit  No               32.7   21    45.3   32.7  28.4  37     32.5  
10 hematocrit  Yes              32.2   21    45.3   32    27.7  36.5   33.7  
11 n_wb_cell   No               11.3    3.3  27.8   10.4   7.7  14     23.3  
12 n_wb_cell   Yes              13.1    3.3  27.8   12.4   8.8  16.8   31.3  
13 potassium   No                4.14   3.1   5.7    4.1   3.8   4.5    0.281
14 potassium   Yes               4.26   3.1   5.7    4.2   3.8   4.7    0.399
15 sodium      No              139.   129   146    139   136   141     11.8  
16 sodium      Yes             138.   129   146    138   135   141     17.4  </code></pre>
</div>
<p>:::</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary plot</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lab_measure) <span class="sc">+</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>thirty_day_mort,<span class="at">y=</span>value)) <span class="sc">+</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="at">facets=</span><span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free'</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>From the graph, we could know that there might have no association between hematocrit and death rate during 30 days after admission of ICU. But for sodium and chloride and bicarbonate, we could observe that the mean and range of those people died during 30 days after admission of ICU are lower than those of people alive during 30 days. On the contrary, for potassium, number of white blood cell, glucose and creatinite, the mean and range of those people died during 30 days after admission of ICU are higher than those of people alive during 30 days.</p>
<ul>
<li><code>thirty_day_mort</code> vs first vital measurements ::: {.cell layout-align=“center”}</li>
</ul>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>vital_measure <span class="ot">&lt;-</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mimic_icu_cohort,<span class="fu">c</span>(<span class="st">'heart_rate'</span>,<span class="st">'ni_blood_pressure'</span>,</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'sni_blood_pressure'</span>,<span class="st">'body_temp'</span>,</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'respiratory_rate'</span>,<span class="st">'thirty_day_mort'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span>heart_rate<span class="sc">:</span>respiratory_rate) <span class="sc">%&gt;%</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(value<span class="sc">&lt;</span><span class="fu">quantile</span>(value,<span class="fl">0.975</span>,<span class="at">na.rm=</span>T) <span class="sc">&amp;</span> </span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>           value<span class="sc">&gt;</span><span class="fu">quantile</span>(value,<span class="fl">0.025</span>,<span class="at">na.rm=</span>T)) <span class="sc">%&gt;%</span></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary table</span></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a>lab_measure <span class="sc">%&gt;%</span></span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name,thirty_day_mort) <span class="sc">%&gt;%</span></span>
<span id="cb94-15"><a href="#cb94-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb94-16"><a href="#cb94-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean=</span><span class="fu">mean</span>(value),</span>
<span id="cb94-17"><a href="#cb94-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">min=</span><span class="fu">min</span>(value),</span>
<span id="cb94-18"><a href="#cb94-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">max=</span><span class="fu">max</span>(value),</span>
<span id="cb94-19"><a href="#cb94-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">median=</span><span class="fu">median</span>(value),</span>
<span id="cb94-20"><a href="#cb94-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">q25=</span><span class="fu">quantile</span>(value,<span class="fl">0.25</span>),</span>
<span id="cb94-21"><a href="#cb94-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">q75=</span><span class="fu">quantile</span>(value,<span class="fl">0.75</span>),</span>
<span id="cb94-22"><a href="#cb94-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">variance=</span><span class="fu">var</span>(value)</span>
<span id="cb94-23"><a href="#cb94-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb94-24"><a href="#cb94-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width=</span><span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 9
# Groups:   name [8]
   name        thirty_day_mort   mean   min   max median   q25   q75 variance
   &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 bicarbonate No               23.1   13.5  31     23    21    25     11.2  
 2 bicarbonate Yes              21.6   14    31.8   21    18    24     16.4  
 3 chloride    No              105.    92   115    105   102   108     23.7  
 4 chloride    Yes             104.    92   115    104   100   108     30.9  
 5 creatinine  No                1.11   0.5   5.2    0.9   0.7   1.2    0.484
 6 creatinine  Yes               1.61   0.5   5.2    1.3   0.9   2      1.03 
 7 glucose     No              134.    75   318    123   104   151   1909.   
 8 glucose     Yes             151.    75   318    139   110   180   2915.   
 9 hematocrit  No               32.7   21    45.3   32.7  28.4  37     32.5  
10 hematocrit  Yes              32.2   21    45.3   32    27.7  36.5   33.7  
11 n_wb_cell   No               11.3    3.3  27.8   10.4   7.7  14     23.3  
12 n_wb_cell   Yes              13.1    3.3  27.8   12.4   8.8  16.8   31.3  
13 potassium   No                4.14   3.1   5.7    4.1   3.8   4.5    0.281
14 potassium   Yes               4.26   3.1   5.7    4.2   3.8   4.7    0.399
15 sodium      No              139.   129   146    139   136   141     11.8  
16 sodium      Yes             138.   129   146    138   135   141     17.4  </code></pre>
</div>
<p>:::</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary plot</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vital_measure) <span class="sc">+</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>thirty_day_mort,<span class="at">y=</span>value)) <span class="sc">+</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="at">facets=</span><span class="fu">vars</span>(name),<span class="at">scales =</span> <span class="st">'free'</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>From the graph, for body temperature, mean non-invasive blood pressure and systolic non-invasive blood pressure, we could observe that the mean and range of those people died during 30 days after admission of ICU are lower than those of people alive during 30 days. On the contrary, for respiratory rate, and heart rate, the mean and range of those people died during 30 days after admission of ICU are higher than those of people alive during 30 days. Body temperate of patients is symmetric and seem to be normal distribution. Heart rate is right skewed.</p>
<p>-<code>thirty_day_mort</code> vs first ICU unit ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary plot</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>thirty_day_mort,mimic_icu_cohort<span class="sc">$</span>first_careunit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      Cardiac Vascular Intensive Care Unit (CVICU) Coronary Care Unit (CCU)
  No                                          9191                     5382
  Yes                                          257                      716
     
      Medical Intensive Care Unit (MICU)
  No                                8823
  Yes                               1384
     
      Medical/Surgical Intensive Care Unit (MICU/SICU) Neuro Intermediate
  No                                              7768               1283
  Yes                                             1051                 28
     
      Neuro Stepdown Neuro Surgical Intensive Care Unit (Neuro SICU)
  No             614                                            1157
  Yes             12                                             223
     
      Surgical Intensive Care Unit (SICU) Trauma SICU (TSICU)
  No                                 7355                6280
  Yes                                 883                 658</code></pre>
</div>
<p>::: ::: {.cell layout-align=“center”}</p>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="sc">%&gt;%</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(thirty_day_mort,first_careunit) <span class="sc">%&gt;%</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(thirty_day_mort,<span class="at">fill=</span>first_careunit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_sol_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<p>::: For patients alive during 30 thirty days in ICU, they tend to be accepted CVICU, MICU/SICU ad MICU for the first care. For patients dead during 30 thirty days in ICU, their most often first care is MICU, MICU/SICU and then SICU.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>